version: "3.8"

services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
        container_name: es-local-test
        environment:
            - node.name=es-node-1
            - cluster.name=es-test-cluster
            - discovery.type=single-node
            - xpack.security.enabled=false
            - xpack.security.enrollment.enabled=false
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports:
            - "9200:9200"
        volumes:
            - es_data:/usr/share/elasticsearch/data
        networks:
            - elastic-net

    express-backend:
        build: ./backend
        ports:
            - "5020:5020"
        environment:
            - NODE_ENV=production
            - ELASTICSEARCH_URL=http://elasticsearch:9200
            - ELASTICSEARCH_INDEX=properties
            - CORS_ORIGIN=http://localhost:3020
        volumes:
            - ./backend:/app
            - /app/node_modules
        depends_on:
            elasticsearch:
                condition: service_healthy # Wait until ES healthcheck passes

        networks:
            - elastic-net
    frontend:
        build: ./frontend
        ports:
            - "3020:3020"
        volumes:
            - ./frontend:/app
            - /app/node_modules
        environment:
            - WDS_SOCKET_PORT=0
            - PORT=3020

    kibana:
        image: docker.elastic.co/kibana/kibana:8.15.0
        container_name: kibana-local-test
        environment:
            - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
        ports:
            - "5601:5601"
        depends_on:
            elasticsearch:
                condition: service_healthy
        networks:
            - elastic-net

volumes:
    es_data:
        driver: local

networks:
    elastic-net:
        driver: bridge
